version: '3'

services:
  
  cockpit:
    build: cockpit
    container_name: cockpit
    # live code reload
    volumes:
      - ./cockpit:/opt/cockpit
    ports:
      - "80:8000"
    devices:
      - /dev/ttyUSB0
    environment:
      - CHASSIS_PORT=/dev/ttyUSB0
  
  ustreamer:
    container_name: ustreamer
    image: pikvm/ustreamer:latest
    command: --host=0.0.0.0 \
             --port=8001 \
             --allow-origin=\* \
             --device=/dev/video0 \
             --device-timeout=5 \
             --workers=4 \
             --encoder=HW \
             --format=MJPEG
    ports:
      - "8001:8001"
    devices:
      - /dev/video0
    stop_grace_period: 1s
