version: '3'

services:
  
  pilesos:
    build: .
    container_name: pilesos
    restart: always
    # live code reload
    volumes:
      - ./pilesos:/app/pilesos
    ports:
      - "80:8000"
    # depends_on:
    #   - pigpiod

  ustreamer:
    container_name: ustreamer
    image: pikvm/ustreamer:latest
    restart: always
    command: --host=0.0.0.0 --port=8001 --allow-origin=\* --workers=1 --device=/dev/video0 
    ports:
      - "8001:8001"
    devices:
      - /dev/video0

  # pigpiod:
  #   container_name: pigpiod
  #   image: zinen2/alpine-pigpiod:latest
  #   entrypoint: pigpiod -g -a 1 -s 10
  #   restart: always
  #   ports:
  #     - 8888
  #   devices: 
  #     - /dev/gpiochip0
  #   privileged: true
