version: '3'

services:
  
  pilesos:
    build: .
    container_name: pilesos
    # live code reload
    volumes:
      - ./pilesos:/app/pilesos
    ports:
      - "80:8000"
    # depends_on:
    #   - pigpiod
    devices:
      - /dev/gpiochip0
      - /dev/gpiomem
    privileged: true
  
  ustreamer:
    container_name: ustreamer
    image: pikvm/ustreamer:latest
    restart: always
    command: --host=0.0.0.0 \
             --port=8001 \
             --allow-origin=\* \
             --device=/dev/video0 
             --device-timeout=2
             --workers=2 \
             --quality=50 \
             --encoder=HW
    ports:
      - "8001:8001"
    devices:
      - /dev/video0
    stop_grace_period: 1s
    
  pigpiod:
    container_name: pigpiod
    image: zinen2/alpine-pigpiod:latest
    entrypoint: pigpiod -g -a 1 -s 10
    ports:
      - 8888
    devices: 
      - /dev/gpiochip0
    privileged: true
